version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 25
    directory: "/"
    commit-message:
      prefix: "update"
      prefix_development: "chore"
      include_scope: true

    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tehran"
