name: Analyze Source Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze Source Code
    env:
      NPM_TOKEN: ${{ secrets.NPM_READ_TOKEN }}

    runs-on:
      - ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true

      - name: Enable Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Typescript Type Check
        run: yarn build:check

      - name: Check Build Production
        run: yarn build
